spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth123}

communicator.secret=${COMMUNICATOR_SECRET:MaithilArt_TopSecret_786}