spring.application.name=inventory-service



server.port= 8089

spring.datasource.url= jdbc:postgresql://auth-db:5432/auth_db
spring.datasource.username= auth_user
spring.datasource.password= auth123
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql= true
#spring.jpa.properties.hibernate.default_schema= cart

communicator.secret=${COMMUNICATOR_SECRET:MaithilArt_Default_Secret_786}

logging.level.root= INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [Trace:%X{pulse}] [Caller:%X{caller}] [%X{method} %X{uri}] %-5level %logger{36} - %msg%n

gateway.secret= ${GATEWAY_SECRET:maithilart-gateway-secret-code-is-rudra}
internal.secret= ${INTERNAL_SECRET:maithilart-internal-secret-code-is-rudra}
jwt.secret=${JWT_SECRET:thisisaverybigsecuritykeywith32bitcharacters-thatwillbeusedinmyapplication.}
jwt.expiration-minutes=15


product.service.url= http://localhost:8085
order.service.url= http://localhost:8087

maithil.event.enabled=true
maithil.event.publisher=communicator
maithil.event.poller.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

maithil.observability.application=maithil-art
maithil.observability.environment=dev